'use strict';;let AxiosError,utils;_ee5‍.x([["default",()=>_ee5‍.o]]);_ee5‍.w("../core/AxiosError.js",[["default",["AxiosError"],function(v){AxiosError=v}]]);_ee5‍.w("../utils.js",[["default",["utils"],function(v){utils=v}]]);




/**
 * A `CanceledError` is an object that is thrown when an operation is canceled.
 *
 * @param {string=} message The message.
 * @param {Object=} config The config.
 * @param {Object=} request The request.
 *
 * @returns {CanceledError} The created error.
 */
function CanceledError(message, config, request) {
  // eslint-disable-next-line no-eq-null,eqeqeq
  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED, config, request);
  this.name = 'CanceledError';
}

utils.inherits(CanceledError, AxiosError, {
  __CANCEL__: true
});

_ee5‍.d(CanceledError);
